name: Build terraform bundler

on:
  # Every push will run this action
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        terraform_core_version: [0.12.31, 0.15.1]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.12.13'
      - uses: actions/checkout@v2
        with:
          repository: 'hashicorp/terraform'
          persist-credentials: 'false'
          ref: ${{ matrix.terraform_core_version }}
          path: my-tools
        