name: Build terraform bundler

on:
  # Every push will run this action
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        terraform_core_version: [v0.12.31, v0.15.1]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'hashicorp-services/terraform-bundler'
          persist-credentials: 'false'
          path: terraform-bundler
          #token: 'when testing locally, an oath token is required'
      - uses: actions/setup-go@v2
        with:
          go-version: '1.12.13'
      - uses: actions/checkout@v2
        with:
          repository: 'hashicorp/terraform'
          persist-credentials: 'false'
          ref: ${{ matrix.terraform_core_version }}
          path: terraform
          #token: 'when testing locally, an oath token is required'
      - run: |
          pwd
          cd terraform
          go install -v ./tools/terraform-bundle
          cd ../..
          pwd
          whereis terraform-bundle
        #mv home/go/bin/terraform-bundle terraform-bundler/terraform-bundler/${{ matrix.terraform_core_version }}/
        #cd terraform-bundler/terraform-bundler/
        #git config --global user.email "team-is@hashicorp.com" 
        #git config --global user.name "GitHub Action"
        #git add * 
         #git commit -m "bundle creation" 
         #git push